import {it,expect} from 'vitest';
import {createSeed} from '@/data/seed';
import {noticeMatches,stagesFor,validateProcedure} from '@/lib/rules';
import {apply,ok,assistant,student} from './fixtures';
import type {Notice} from '@/lib/types';
it('절차 임시저장은 게시 데이터 불변',()=>{const s=createSeed(),d=structuredClone(s.departments[0]);d.stages[0].dueDate='2026-10-03T18:00';const saved=ok(s,assistant,{type:'saveProcedure',department:d});expect(saved.departments).toEqual(s.departments);expect(saved.procedureDrafts[d.id].stages[0].dueDate).toBe(d.stages[0].dueDate);});
it('절차 게시 날짜 변경 배지·알림 및 교수/학생 정보 불변',()=>{const s=createSeed(),d=structuredClone(s.departments[0]);d.stages[0].dueDate='2026-10-03T18:00';const updated=ok(s,assistant,{type:'publishProcedure',department:d});expect(updated.departments[0].stages[0].changedAt).toBeTruthy();expect(updated.notifications).toHaveLength(2);expect(updated.professors).toEqual(s.professors);expect(updated.students).toEqual(s.students);expect(updated.sections).toEqual(s.sections);});
it('마지막 추가·삭제가 게시 후 반영',()=>{const s=createSeed(),d=structuredClone(s.departments[0]);d.stages=[...d.stages.slice(0,3),{...d.stages[3],id:'new'}];const updated=ok(s,assistant,{type:'publishProcedure',department:d});expect(updated.departments[0].stages.map(s=>s.id)).toEqual(['apply','plan','writing','new']);});
it('학생/다른 학과 조교는 절차 쓰기 불가',()=>{const s=createSeed();expect(apply(s,student,{type:'publishProcedure',department:s.departments[0]}).error).toBeTruthy();expect(apply(s,assistant,{type:'publishProcedure',department:s.departments[1]}).error).toBeTruthy();});
it('조교의 제출·초안 위조는 학생 및 지도교수 데이터를 바꾸지 못함',()=>{
 const s=createSeed();const fake={id:'fake',studentId:'student-1',departmentId:'psychology',stageId:'application',professorId:'prof-psych',title:'위조',summary:'위조',body:'위조',meetingWanted:false,savedAt:''};
 for(const type of ['saveDraft','sendApplication','sendSubmission'] as const)expect(apply(s,assistant,{type,draft:fake}).state).toBe(s);
});
it('수업형으로 게시하면 신청 단계 제거 및 두 방식만 허용',()=>{const s=createSeed(),d={...s.departments[0],method:'course' as const};const updated=ok(s,assistant,{type:'publishProcedure',department:d});expect(updated.departments[0].stages.some(s=>['application','approval'].includes(s.kind))).toBe(false);expect(validateProcedure({...d,method:'invalid' as never})).toBeTruthy();});
it('역전 날짜와 누락 필드는 게시 실패',()=>{const d=structuredClone(createSeed().departments[0]);d.stages[0].startDate='2026-09-01T09:00';d.stages[0].dateStatus='CONFIRMED';d.stages[0].dueDate='2026-08-01T18:00';expect(validateProcedure(d)).toBeTruthy();d.stages[0].dueDate='';expect(validateProcedure(d)).toBeTruthy();});
it('공지는 학기·전공 유형·졸업예정 대상만 표시·알림',()=>{let s=createSeed();const n:Notice={id:'',departmentId:'psychology',title:'새 공지',body:'안내',semester:'2026-2',graduationSemester:'2027년 2월',target:'primary',stageId:'plan',eventAt:'2026-10-02T10:00',savedAt:''};s=ok(s,assistant,{type:'publishNotice',notice:n});expect(s.notifications).toHaveLength(1);expect(noticeMatches(s.notices[0],s.students[0],s.departments[0])).toBe(true);expect(noticeMatches(s.notices[0],s.students[2],s.departments[0])).toBe(false);});
it('단계 대상 구분과 요건 누락은 면제 처리와 구별',()=>{const s=createSeed(),d=s.departments[1];d.stages[0].target='primary';expect(stagesFor(s.students[0],d).some(v=>v.id===d.stages[0].id)).toBe(false);delete (d.requirements as Partial<typeof d.requirements>).secondary;expect(stagesFor(s.students[0],d)).toHaveLength(0);expect(d.requirements.secondary).toBeUndefined();});
