"use client";
import {useState} from 'react';
import {useBoardStore} from '@/lib/store';
import {advisorFor,applicationFor,majorRole,progress,stageStatus} from '@/lib/rules';
import type {Department,Notice,Stage,Student,Target,StepKind} from '@/lib/types';
import {Badge,Avatar,colorFor,dateLabel,FeedbackView,FileInput} from './ui';
import {Roadmap} from './roadmap';
const kindLabels:Record<StepKind,string>={application:'신청 제출',approval:'교수 승인',plan:'연구계획서 검토',final:'최종논문 검토',task:'활동 완료 기록',course:'수강 확인'};
export function AdminBoard(){
 const state=useBoardStore(),assistant=state.assistants.find(a=>a.id===state.assistantId)!,d=state.departments.find(d=>d.id===assistant.departmentId)!;
 const [tab,setTab]=useState('procedure');
 return <div className="space-y-6"><header><p className="label">{d.name} · 학과 조교</p><h1 className="text-2xl font-extrabold">{assistant.name}</h1><p className="mt-2 text-sm text-slate-500">절차와 공지를 게시하고, 학생의 진행 상황을 확인하세요.</p></header><div role="tablist" aria-label="조교 업무" className="flex gap-2">{[['procedure','졸업논문 절차'],['notices','공지 작성'],['students','학과 학생 검색']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'btn':'btn-alt'} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='procedure'&&<ProcedureEditor key={d.id} department={d}/>}
 {tab==='notices'&&<NoticeEditor key={d.id} department={d}/>}
 {tab==='students'&&<StudentDirectory department={d}/>}
 </div>;
}
function ProcedureEditor({department:published}:{department:Department}){
 const state=useBoardStore(),actor={role:'assistant' as const,id:state.assistantId},d=state.procedureDrafts[published.id]??published;
 const [drag,setDrag]=useState<number|null>(null),[message,setMessage]=useState('');
 const update=(patch:Partial<Department>)=>state.act(actor,{type:'saveProcedure',department:{...d,...patch}});
 const change=(id:string,patch:Partial<Stage>)=>update({stages:d.stages.map(s=>s.id===id?{...s,...patch}:s)});
 const move=(from:number,to:number)=>{if(to<0||to>=d.stages.length||from===to)return;const stages=[...d.stages];const [stage]=stages.splice(from,1);stages.splice(to,0,stage);update({stages});};
 const preview:Student={id:'preview',name:'미리보기 학생',studentNo:'',graduationSemester:d.graduationSemester,registeredSemesters:8,majors:[{departmentId:d.id,role:'primary'}],enrollmentIds:[]};
 return <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]"><section className="card space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="section-title">졸업논문 절차 편집기</h2><Badge>작성 중</Badge></div><p className="text-xs text-slate-500">자동 임시저장 · {state.procedureSavedAt[d.id]?dateLabel(state.procedureSavedAt[d.id]):'게시된 절차를 편집합니다.'} · 게시 전에는 학생 화면이 바뀌지 않습니다.</p><div className="grid gap-3 sm:grid-cols-2"><label className="field-label">적용 학기<input value={d.semester} onChange={e=>update({semester:e.target.value})}/></label><label className="field-label">대상 졸업예정 학기<input value={d.graduationSemester} onChange={e=>update({graduationSemester:e.target.value})}/></label><label className="field-label sm:col-span-2">지도교수 결정 방식<select value={d.method} onChange={e=>update({method:e.target.value as Department['method']})}><option value="application">신청·승인형</option><option value="course">수업형</option></select></label></div>{d.method==='course'&&<p className="rounded-xl bg-sky-50 p-3 text-sm">수강 분반 정보를 사용합니다. 신청·승인 단계는 게시할 때 제외됩니다.</p>}
 <ol className="space-y-3" aria-label="절차 단계 편집">{d.stages.map((step,i)=><li className="rounded-xl border p-3" key={step.id} draggable onDragStart={e=>{setDrag(i);e.dataTransfer.effectAllowed='move';}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag!==null)move(drag,i);setDrag(null);}}>
  <div className="mb-3 flex flex-wrap items-center gap-2"><span aria-label="드래그 핸들" className="cursor-grab font-bold">⠿ {i+1}</span><b className="min-w-0 flex-1 text-sm">{step.name||'새 단계'}</b><button className="btn-alt" aria-label={step.name+' 위로'} disabled={i===0} onClick={()=>move(i,i-1)}>↑</button><button className="btn-alt" aria-label={step.name+' 아래로'} disabled={i===d.stages.length-1} onClick={()=>move(i,i+1)}>↓</button><button className="btn-alt" aria-label={step.name+' 삭제'} onClick={()=>update({stages:d.stages.filter(s=>s.id!==step.id)})}>삭제</button></div>
  <details open={i===0}><summary className="cursor-pointer text-sm font-bold">단계 설정</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">
  <label className="field-label sm:col-span-2">단계명<input value={step.name} onChange={e=>change(step.id,{name:e.target.value})}/></label>
  <label className="field-label">진행 방식<select value={step.kind} onChange={e=>change(step.id,{kind:e.target.value as StepKind})}>{Object.entries(kindLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="field-label">대상<select value={step.target} onChange={e=>change(step.id,{target:e.target.value as Target})}><option value="all">전체</option><option value="primary">주전공</option><option value="secondary">복수전공</option></select></label>
  <label className="field-label">시작일<input type="datetime-local" value={step.startDate} onChange={e=>change(step.id,{startDate:e.target.value})}/></label><label className="field-label">마감일<input type="datetime-local" value={step.dueDate} onChange={e=>change(step.id,{dueDate:e.target.value})}/></label>
  <label className="field-label">제출물<input value={step.documents} onChange={e=>change(step.id,{documents:e.target.value})}/></label><label className="field-label">제출처<input value={step.submissionMethod} onChange={e=>change(step.id,{submissionMethod:e.target.value})}/></label>
  <label className="field-label sm:col-span-2">단계 설명<textarea value={step.description} onChange={e=>change(step.id,{description:e.target.value})}/></label><label className="field-label sm:col-span-2">예외사항·유의사항<input value={step.notes} onChange={e=>change(step.id,{notes:e.target.value})}/></label><label className="field-label">담당 연락처<input value={step.contact} onChange={e=>change(step.id,{contact:e.target.value})}/></label>{step.kind==='course'&&<label className="field-label">수업 코드<input value={step.courseId??''} onChange={e=>change(step.id,{courseId:e.target.value})}/></label>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={step.required} onChange={e=>change(step.id,{required:e.target.checked})}/>필수 단계</label><div className="sm:col-span-2"><FileInput value={step.file} label="관련 서식" onChange={file=>change(step.id,{file})}/></div>
  </div></details>
 </li>)}</ol><button className="btn-alt" onClick={()=>update({stages:[...d.stages,{id:crypto.randomUUID(),name:'새 단계',kind:'task',startDate:'2026-09-01T09:00',dueDate:'2026-12-18T18:00',description:'새 단계 안내',target:'all',documents:'제출물',submissionMethod:'서비스 내 제출',notes:'',contact:'demo@example.invalid',required:true}]})}>단계 추가</button><div className="flex gap-2 border-t pt-4"><button className="btn-alt" onClick={()=>{if(update({}))setMessage('임시저장 완료');}}>절차 임시저장</button><button className="btn" onClick={()=>{if(state.act(actor,{type:'publishProcedure',department:d}))setMessage('게시 완료 · 학생에게 알림을 보냈습니다.');}}>절차 게시</button></div><p role="status" className="text-sm text-emerald-700">{message}</p></section>
 <aside className="card lg:sticky lg:top-5"><h2 className="section-title mb-4">학생 로드맵 미리보기</h2><Badge className={colorFor(d)}>{d.name} · {d.semester}</Badge><div className="mt-5"><Roadmap state={state} student={preview} department={d} preview/></div></aside></div>;
}
function NoticeEditor({department:d}:{department:Department}){
 const state=useBoardStore(),assistantId=state.assistantId;
 const empty:Notice={id:'',departmentId:d.id,title:'',body:'',semester:d.semester,graduationSemester:'',target:'all',stageId:'',eventAt:'',savedAt:''};
 const n=state.noticeDrafts[assistantId]??empty, [message,setMessage]=useState('');
 const save=(patch:Partial<Notice>)=>state.act({role:'assistant',id:assistantId},{type:'saveNotice',notice:{...n,...patch}});
 return <section className="card space-y-4"><div className="flex items-center justify-between"><h2 className="section-title">공지사항 작성</h2><button className="btn-alt" onClick={()=>save(empty)}>새 공지</button></div><p className="text-xs text-slate-500">자동 저장 · {n.savedAt?dateLabel(n.savedAt):'작성 전'}</p><label className="field-label">공지 제목<input value={n.title} onChange={e=>save({title:e.target.value})}/></label><label className="field-label">공지 본문<textarea rows={5} value={n.body} onChange={e=>save({body:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="field-label">공지 적용 학기<input value={n.semester} onChange={e=>save({semester:e.target.value})}/></label><label className="field-label">공지 대상<select value={n.target} onChange={e=>save({target:e.target.value as Target})}><option value="all">전체</option><option value="primary">주전공</option><option value="secondary">복수전공</option></select></label><label className="field-label">졸업예정 학기 필터<input placeholder="비우면 전체" value={n.graduationSemester} onChange={e=>save({graduationSemester:e.target.value})}/></label><label className="field-label">연결 단계<select value={n.stageId} onChange={e=>save({stageId:e.target.value})}><option value="">연결 없음</option>{d.stages.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field-label">공지 일정 (선택)<input type="datetime-local" value={n.eventAt} onChange={e=>save({eventAt:e.target.value})}/></label></div><FileInput label="공지 첨부" value={n.file} onChange={file=>save({file})}/><div className="flex gap-2"><button className="btn-alt" onClick={()=>{if(save({}))setMessage('임시저장 완료');}}>공지 임시저장</button><button className="btn" onClick={()=>{if(state.act({role:'assistant',id:assistantId},{type:'publishNotice',notice:n}))setMessage('공지 게시 완료');}}>공지 게시</button></div><p role="status" className="text-sm text-emerald-700">{message}</p></section>;
}
function StudentDirectory({department:d}:{department:Department}){
 const state=useBoardStore(),[query,setQuery]=useState(''),[graduation,setGraduation]=useState(''),[extended,setExtended]=useState(false),[role,setRole]=useState(''),[stage,setStage]=useState(''),[delayed,setDelayed]=useState(false),[selected,setSelected]=useState('');
 const all=state.students.filter(s=>s.majors.some(m=>m.departmentId===d.id));
 const rows=all.filter(s=>(s.name+s.studentNo).includes(query)&&(!graduation||s.graduationSemester===graduation)&&(!extended||s.registeredSemesters>8)&&(!role||majorRole(s,d.id)===role)&&(!stage||progress(state,s,d).current?.id===stage)&&(!delayed||progress(state,s,d).steps.some(step=>stageStatus(state,s,d,step,new Date().toISOString())==='마감 지남')));
 const student=all.find(s=>s.id===selected),app=student&&applicationFor(state,student.id,d.id);
 return <section className="space-y-5"><div className="card"><h2 className="section-title">학과 학생 전원 조회</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="field-label">이름·학번 검색<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="field-label">졸업예정 학기<select aria-label="졸업예정 학기" value={graduation} onChange={e=>setGraduation(e.target.value)}><option value="">전체 학기</option>{[...new Set(all.map(s=>s.graduationSemester))].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-label">전공 유형<select value={role} onChange={e=>setRole(e.target.value)}><option value="">전체</option><option value="primary">주전공</option><option value="secondary">복수전공</option></select></label><label className="field-label">현재 진행 단계<select aria-label="현재 진행 단계" value={stage} onChange={e=>setStage(e.target.value)}><option value="">전체</option>{d.stages.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={extended} onChange={e=>setExtended(e.target.checked)}/>초과학기만</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={delayed} onChange={e=>setDelayed(e.target.checked)}/>지연 학생만</label></div><p className="my-4 text-sm">검색 결과 {rows.length}명 / 소속 학생 {all.length}명</p><div className="overflow-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr>{['학생','학번','학적','지도교수','현재 단계','다음 마감'].map(t=><th className="border-b p-2" key={t}>{t}</th>)}</tr></thead><tbody>{rows.map(s=>{const pr=progress(state,s,d);return <tr key={s.id}><td className="p-2"><button className="flex items-center gap-2 font-bold text-snu" onClick={()=>setSelected(s.id)}><Avatar name={s.name}/>{s.name}</button></td><td className="p-2">{s.studentNo}</td><td className="p-2"><Badge>{s.graduationSemester}</Badge><Badge>{majorRole(s,d.id)==='primary'?'주전공':'복수전공'}</Badge>{s.registeredSemesters>8&&<Badge>초과학기</Badge>}</td><td className="p-2">{advisorFor(state,s,d)?.name??'미정'}</td><td className="p-2">{pr.current?.name??'완료/면제'}</td><td className="p-2">{pr.current?dateLabel(pr.current.dueDate):'—'}</td></tr>;})}</tbody></table></div></div>
 {student&&<article className="card"><div className="mb-4 flex justify-between"><h2 className="section-title">{student.name} 진행 현황</h2><Badge>읽기 전용</Badge></div><p className="my-3 text-sm">지도교수: {advisorFor(state,student,d)?.name??'미정'} · 신청: {app?.status??'미신청'}</p><FeedbackView value={app?.feedback}/><Roadmap state={state} student={student} department={d} preview/></article>}</section>;
}
