"use client";
import {departments} from "@/data/departments";
import {adminRows} from "@/lib/rules";
import {useBoardStore} from "@/lib/store";
import {useState} from "react";
export function AdminBoard(){
  const state=useBoardStore(), [filter,setFilter]=useState("all"), [feedback,setFeedback]=useState<Record<string,string>>({}), [assignments,setAssignments]=useState<Record<string,string>>({});
  const rows=adminRows(state,departments,filter), pending=rows.filter(r=>r.reason!=="확정"), reviews=rows.filter(r=>r.app?.status==="승인" && r.app.adminReview!=="검토 완료");
  const studentIds=new Set(rows.map(r=>r.student.id)), completeIds=[...studentIds].filter(id=>rows.filter(r=>r.student.id===id).every(r=>r.index>=r.department.stages.length));
  return <div className="space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><p className="label">행정실 화면</p><h1 className="text-3xl font-extrabold">학과별 진행 현황</h1></div><label>학과 필터<select aria-label="학과 필터" className="ml-2 rounded-xl border bg-white p-2" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 학과</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></header>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["대상 학생",studentIds.size],["미확정 전공",pending.length],["확정 검토 대기",reviews.length],["심사 대기 전공",rows.filter(r=>r.department.stages[r.index]?.review).length],["전체 절차 완료 학생",completeIds.length]].map(([label,count])=><div className="card" data-testid={"metric-"+label} key={label}><p className="label">{label}</p><p className="text-3xl font-extrabold">{count}</p></div>)}</section><p className="text-sm text-slate-500">대상·완료는 학생 수, 미확정·검토 대기는 학생-전공 건수입니다. 완료는 선택 학과의 모든 단계가 끝난 학생만 집계합니다.</p>
    <section className="card"><h2 className="text-xl font-extrabold">수업 기반 지도교수 배정</h2>{rows.filter(r=>r.department.method==="course_assigned" && !r.app).map(r=>{
      const key=r.student.id+r.department.id, professors=state.professors.filter(p=>p.departmentId===r.department.id);
      return <div className="mt-3 flex flex-wrap items-center gap-3 rounded-xl bg-sky-50 p-3" key={key}><span>{r.student.name} · {r.department.name}</span><select aria-label={r.student.name+" 배정 교수"} className="max-w-full rounded border bg-white p-2" value={assignments[key] ?? professors[0]?.id ?? ""} onChange={e=>setAssignments({...assignments,[key]:e.target.value})}>{professors.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="btn" disabled={!professors.length} onClick={()=>state.assignCourseAdvisor(r.student.id,r.department.id,assignments[key]??professors[0].id)}>지도교수 배정</button></div>;
    })}</section>
    <section className="card"><h2 className="text-xl font-extrabold">교수별 지도 정원</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{state.professors.filter(p=>filter==="all" || p.departmentId===filter).map(p=><div className="rounded-xl bg-slate-50 p-3" key={p.id}><b>{p.name}</b> · {departments.find(d=>d.id===p.departmentId)?.name}<p>{p.capacity===null?"정원 미적용":"총 "+p.capacity+"명 · 배정 "+p.assigned+"명 · 잔여 "+(p.capacity-p.assigned)+"명"}</p></div>)}</div></section>
    <section><h2 className="mb-3 text-xl font-extrabold">교수 승인 건 확정 검토</h2>{reviews.length===0 && <p className="card">검토 대기 건이 없습니다.</p>}{reviews.map(r=><article className="card mb-3" key={r.app!.id}><h3 className="font-extrabold">{r.student.name} · {r.department.name}</h3><p>{r.professor?.name} · {r.app!.topic} · {r.app!.adminReview}</p><label className="mt-3 block">행정실 피드백<input aria-label="행정실 피드백" className="mt-1 w-full rounded border p-2" value={feedback[r.app!.id]??""} onChange={e=>setFeedback({...feedback,[r.app!.id]:e.target.value})}/></label><div className="mt-3 flex gap-2"><button className="btn" onClick={()=>state.reviewApplication(r.app!.id,"검토 완료")}>검토 완료</button><button className="btn-alt" onClick={()=>{if(!state.reviewApplication(r.app!.id,"보완 요청",feedback[r.app!.id]))alert("보완 요청 사유를 입력해 주세요.");}}>보완 요청</button></div></article>)}</section>
    <section className="card"><h2 className="text-xl font-extrabold">사유별 미확정 학생</h2>{[...new Set(pending.map(r=>r.reason))].map(reason=><div className="mt-3" key={reason}><h3 className="font-bold">{reason} ({pending.filter(r=>r.reason===reason).length})</h3>{pending.filter(r=>r.reason===reason).map(r=><p key={r.student.id+r.department.id}>{r.student.name} · {r.department.name} {r.app?.feedback && "· "+r.app.feedback}</p>)}</div>)}</section>
    <section className="card"><h2 className="text-xl font-extrabold">학생별·전공별 진행 상황 및 신청 현황</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{rows.map(r=><article className="rounded-xl border p-4" key={r.student.id+r.department.id}><h3 className="font-bold">{r.student.name} · {r.department.name} · {r.role==="primary"?"주전공":"복수전공"}</h3><p>신청: {r.app?.status??"미신청"} · 지도교수: {r.professor?.name??"미배정"}</p><p>현재 단계: {r.department.stages[r.index]?.name??"전체 완료"}</p><p>확정 검토: {r.app?.adminReview??"해당 없음"}</p>{r.department.stages.map((s,i)=><p className="text-sm" key={s.id}>{s.name}: {i<r.index?"완료":i===r.index?"진행 중":"예정"}</p>)}{state.submissions.filter(s=>s.studentId===r.student.id && s.departmentId===r.department.id).map(s=><p className="mt-1 text-sm text-emerald-700" key={s.stageId}>{r.department.stages.find(stage=>stage.id===s.stageId)?.name} 제출 완료 · {new Date(s.at).toLocaleString("ko-KR")}</p>)}</article>)}</div></section>
    <section className="card"><h2 className="text-xl font-extrabold">변경 이력</h2><ul className="mt-3 max-h-80 space-y-3 overflow-auto">{[...state.histories].reverse().map(h=><li key={h.id}><b>{h.actor}</b> · {h.detail}<time className="block text-xs text-slate-500" dateTime={h.at}>{new Date(h.at).toLocaleString("ko-KR")}</time></li>)}</ul></section>
    <section className="card"><h2 className="text-xl font-extrabold">준비 중</h2><div className="mt-3 flex flex-wrap gap-2">{["학생 명단 등록","학과 추가·편집","요건 관리","공지 등록","명단 내보내기"].map(name=><button disabled className="btn-alt" key={name}>{name} · 준비 중</button>)}</div></section>
  </div>;
}
