"use client";
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {useBoardStore} from '@/lib/store';
import type {Actor} from '@/lib/types';
import {dateLabel} from './ui';
const links=[['학생','/student'],['교수','/professor'],['학과 조교','/admin']];
export function BoardShell({children}:{children:React.ReactNode}){
 const path=usePathname(),state=useBoardStore(),[ready,setReady]=useState(false),[open,setOpen]=useState(false);
 useEffect(()=>setReady(true),[]);
 const role:Actor['role']=path==='/professor'?'professor':path==='/admin'?'assistant':'student';
 const id=role==='student'?state.studentId:role==='professor'?state.professorId:state.assistantId;
 const people=role==='student'?state.students:role==='professor'?state.professors:state.assistants;
 const notifications=state.notifications.filter(n=>n.recipientId===id).slice().reverse();
 return <><header className="border-b bg-white"><div className="mx-auto max-w-7xl px-4 py-2"><div className="flex flex-wrap items-center justify-between gap-2"><Link href="/" className="text-xl font-extrabold text-snu">샤논</Link><div className="flex items-center gap-2">{ready&&<select aria-label="데모 사용자" value={id} onChange={e=>{state.choose(role,e.target.value);setOpen(false);}} className="max-w-36 rounded-lg border p-1.5 text-sm">{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<button className="rounded-lg border px-2 py-1.5 text-xs" aria-label="알림" aria-expanded={open} onClick={()=>setOpen(!open)}>알림 {ready?notifications.filter(n=>!n.read).length:0}</button></div></div><div className="mt-2 flex flex-wrap items-center justify-end gap-x-3 gap-y-1 border-t border-slate-100 pt-2 text-[11px] text-slate-500"><nav aria-label="데모 역할 전환" className="flex items-center gap-2"><span>데모 역할 전환</span>{links.map(([label,href])=><Link key={href} href={href} aria-current={path===href?'page':undefined} className={path===href?'font-bold text-snu underline underline-offset-4':'hover:text-snu'}>{label}</Link>)}</nav><details className="relative"><summary className="cursor-pointer">데모 안내 · 일부 일정 가정</summary><aside className="absolute right-0 z-50 mt-2 max-h-80 w-72 max-w-[calc(100vw-2rem)] overflow-y-auto rounded-xl border bg-white p-4 text-xs leading-relaxed shadow-lg" aria-label="데모 데이터 안내"><p className="font-bold">비공식 데모 · 실제 학사 처리 아님</p><p>인물·연락처·정원은 가상이며 브라우저별로 저장됩니다. 팀원 간 상태는 동기화되지 않습니다. 최신 학사 요건은 반드시 학과에 확인하세요.</p>{ready&&state.departments.map(d=><details key={d.id} className="mt-3"><summary className="cursor-pointer font-bold">{d.name} 자료·가정</summary><p>{d.sourceDescription}</p>{d.stages.map(step=><p className="mt-2" key={step.id}><b>{step.name}</b> · {step.dateNote} {step.notes}</p>)}</details>)}</aside></details><button className="underline underline-offset-2" onClick={()=>{if(confirm('현재 학과 자료 데모의 저장 내용을 초기화할까요?'))state.reset();}}>데모 초기화</button></div></div></header>
 {ready&&open&&<aside aria-label="알림 목록" className="mx-auto max-w-7xl p-4"><div className="card max-h-80 overflow-y-auto"><h2 className="font-bold">내 알림</h2>{notifications.length?notifications.map(n=><a className={'mt-2 block rounded-xl p-3 text-sm '+(n.read?'bg-slate-50':'bg-snu-50 font-bold')} key={n.id} href={n.href} onClick={()=>{state.act({role,id},{type:'readNotification',id:n.id});setOpen(false);}}>{!n.read&&'● '}{n.text}<time className="block text-xs font-normal text-slate-500">{dateLabel(n.at)}</time></a>):<p className="mt-3 text-sm text-slate-500">새 알림이 없습니다.</p>}</div></aside>}
 <main className="mx-auto max-w-7xl px-4 py-4">{ready?<>{state.error&&<div role="alert" className="mb-4 flex items-center justify-between gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{state.error}<button onClick={state.clearError}>닫기</button></div>}{children}</>:<p>저장된 데모를 불러오는 중…</p>}</main><footer className="px-4 pb-8 text-center text-xs text-slate-500">샤논 · 졸업논문 진행 관리</footer></>;
}
