"use client";
import {useState} from 'react';
import type {BoardState,Student} from '@/lib/types';
import {deadlinesFor,noticeMatches,stagesFor} from '@/lib/rules';
import {colorFor,dateLabel} from './ui';
export function Calendar({state,student,onSelect}:{state:BoardState;student:Student;onSelect:(departmentId:string,target:string)=>void}){
 const depts=state.departments.filter(d=>student.majors.some(m=>m.departmentId===d.id));
 const [view,setView]=useState('month'),[month,setMonth]=useState(()=>depts.flatMap(d=>stagesFor(student,d).map(s=>s.dueDate)).filter(Boolean).sort()[0]?.slice(0,7)??new Date().toISOString().slice(0,7)),[hidden,setHidden]=useState<string[]>([]);
 const all=depts.flatMap(d=>[
  ...stagesFor(student,d).flatMap(s=>deadlinesFor(state,student.id,d,s).map(v=>({id:'stage-'+d.id+s.id+v.condition,date:v.deadline,start:s.startDate||v.deadline,title:s.name+(v.condition?' · '+v.condition:''),d,target:'step-'+s.id}))),
  ...state.meetings.filter(m=>m.studentId===student.id&&m.departmentId===d.id&&m.selected).map(m=>({id:m.id,date:m.selected!,start:m.selected!,title:'면담 '+m.status,d,target:'meetings'})),
  ...state.notices.filter(n=>noticeMatches(n,student,d)&&n.eventAt).map(n=>({id:n.id,date:n.eventAt,start:n.eventAt,title:n.title,d,target:'notices'})),
 ]).sort((a,b)=>a.date.localeCompare(b.date));
 const events=all.filter(e=>!hidden.includes(e.d.id)&&(view==='month'?e.date.startsWith(month):e.start.slice(0,7)<=month&&e.date.slice(0,7)>=month));
 const first=new Date(month+'-01T12:00:00'),days=new Date(first.getFullYear(),first.getMonth()+1,0).getDate();
 const move=(amount:number)=>{const d=new Date(first);d.setMonth(d.getMonth()+amount);setMonth(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'));};
 return <section className="card" aria-label="통합 캘린더"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">모든 전공 일정</h2><div className="flex gap-2"><button className={view==='month'?'btn':'btn-alt'} onClick={()=>setView('month')}>월간 달력</button><button className={view==='timeline'?'btn':'btn-alt'} onClick={()=>setView('timeline')}>타임라인 보기</button></div></div><div className="my-4 flex flex-wrap items-center gap-2"><button aria-label="이전 달" className="btn-alt" onClick={()=>move(-1)}>←</button><input aria-label="캘린더 월" type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/><button aria-label="다음 달" className="btn-alt" onClick={()=>move(1)}>→</button>{depts.map(d=><label className={'badge border '+colorFor(d)} key={d.id}><input type="checkbox" checked={!hidden.includes(d.id)} onChange={()=>setHidden(hidden.includes(d.id)?hidden.filter(id=>id!==d.id):[...hidden,d.id])}/>{d.name}</label>)}</div>
 {view==='month'?<div className="grid grid-cols-7 gap-1" aria-label="월간 일정">{['일','월','화','수','목','금','토'].map(d=><span key={d} className="text-center text-xs text-slate-500">{d}</span>)}{Array.from({length:first.getDay()},(_,i)=><div key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const day=month+'-'+String(i+1).padStart(2,'0');const daily=events.filter(e=>e.date.startsWith(day));return <div className="min-h-24 min-w-0 rounded border border-slate-100 p-1" key={day}><span className="text-xs">{i+1}</span>{daily.map(e=><button key={e.id} title={e.d.name+' · '+e.title+' · '+dateLabel(e.date)} className={'mt-1 block w-full break-words rounded p-1 text-left text-[10px] leading-tight sm:text-xs '+colorFor(e.d)} onClick={()=>onSelect(e.d.id,e.target)}>{e.title}</button>)}</div>;})}</div>
 :<div className="relative min-w-0 max-w-full overflow-x-auto" aria-label="간트 일정"><div className="min-w-[680px]"><div className="ml-40 grid" style={{gridTemplateColumns:'repeat('+days+',1fr)'}}>{Array.from({length:days},(_,i)=><span className="text-[10px]" key={i}>{i+1}</span>)}</div>{events.map(e=><div key={e.id} className="my-2 flex items-center gap-2"><span className="w-36 shrink-0 truncate text-xs">{e.d.name} · {e.title}</span><div className="grid min-w-0 flex-1 rounded bg-slate-50" style={{gridTemplateColumns:'repeat('+days+',1fr)'}}><button title={e.title} aria-label={e.title} className={'rounded p-1 text-xs '+colorFor(e.d)} style={{gridColumn:(e.start.startsWith(month)?Number(e.start.slice(8,10)):1)+' / '+((e.date.startsWith(month)?Number(e.date.slice(8,10)):days)+1)}} onClick={()=>onSelect(e.d.id,e.target)}>●</button></div></div>)}</div></div>}
 {!events.length&&<p className="mt-4 text-sm text-slate-500">선택한 달에 일정이 없습니다.</p>}</section>;
}
