"use client";
import {useState} from 'react';
import {dateLabel} from './ui';
export function MeetingGrid({value,onChange,allowed,readOnly=false}:{value:string[];onChange:(v:string[])=>void;allowed?:string[];readOnly?:boolean}){
 const [day,setDay]=useState(allowed?.[0]?.slice(0,10)??new Date(Date.now()+86400000).toISOString().slice(0,10));
 const [painting,setPainting]=useState<'add'|'remove'|null>(null);
 const days=allowed?[...new Set(allowed.map(s=>s.slice(0,10)))]:Array.from({length:3},(_,i)=>{const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+i);return d.toISOString().slice(0,10);});
 const times=Array.from({length:18},(_,i)=>String(9+Math.floor(i/2)).padStart(2,'0')+':'+(i%2?'30':'00'));
 const paint=(slot:string,mode:'add'|'remove')=>onChange(mode==='add'?[...new Set([...value,slot])]:value.filter(v=>v!==slot));
 return <div onPointerUp={()=>setPainting(null)} onPointerLeave={()=>setPainting(null)}>{!allowed&&<label className="field-label">면담 시작 날짜<input type="date" value={day} onChange={e=>e.target.value&&setDay(e.target.value)}/></label>}<p className="my-2 text-xs text-slate-500">{allowed?'제안된 시간 중 하나를 선택하세요.':'클릭 또는 드래그로 30분 단위 시간을 선택하세요. 키보드로도 선택할 수 있습니다.'}</p><div className="overflow-auto"><div className="meeting-grid" style={{gridTemplateColumns:'50px repeat('+days.length+', minmax(85px, 1fr))'}}><span/>{days.map(d=><b className="text-xs" key={d}>{d.slice(5)}</b>)}{times.map(t=><div className="contents" key={t}><span className="text-xs text-slate-500">{t}</span>{days.map(d=>{const slot=d+'T'+t,selected=value.includes(slot),disabled=readOnly||!!allowed&&!allowed.includes(slot);return <button type="button" key={slot} disabled={disabled} aria-label={slot} aria-pressed={selected} className={'slot '+(selected?'bg-snu text-white':allowed?.includes(slot)?'bg-snu-100':'bg-slate-100')} onPointerDown={()=>{if(allowed)return;setPainting(selected?'remove':'add');paint(slot,selected?'remove':'add');}} onPointerEnter={()=>{if(painting&&!allowed)paint(slot,painting);}} onClick={e=>{if(allowed)onChange([slot]);else if(e.detail===0)paint(slot,selected?'remove':'add');}}>{selected?'✓':allowed?.includes(slot)?'가능':''}</button>;})}</div>)}</div></div><p className="mt-2 text-sm">{value.length?'선택: '+value.map(dateLabel).join(', '):'선택된 시간 없음'}</p></div>;
}
