"use client";
import {useEffect,useState} from 'react';
import {useBoardStore} from '@/lib/store';
import {advisorFor,approvedCount,majorRole,progress} from '@/lib/rules';
import type {Application,Submission} from '@/lib/types';
import {Avatar,Badge,dateLabel,FeedbackView,FileView} from './ui';
import {MeetingGrid} from './meeting-grid';
import {useSavedForm} from './use-saved-form';
import {StageBadges} from './stage-metadata';
const tabs=[['students','내 지도 학생'],['applications','지도 신청'],['meetings','면담 일정'],['plan','연구계획서 검토'],['final','최종논문 검토']];
export function ProfessorBoard(){
 const state=useBoardStore(),p=state.professors.find(p=>p.id===state.professorId)!;
 const [tab,setTab]=useState('students'),[filter,setFilter]=useState('all');
 useEffect(()=>{const update=()=>{const t=new URLSearchParams(window.location.search).get('tab');setTab(t&&tabs.some(([id])=>id===t)?t:'students');};update();window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update);},[]);
 const advisees=state.students.filter(s=>s.majors.some(m=>{const d=state.departments.find(d=>d.id===m.departmentId);return d&&advisorFor(state,s,d)?.id===p.id;}));
 const applications=state.applications.filter(a=>a.professorId===p.id);
 return <div className="space-y-6"><header className="flex items-center gap-3"><Avatar name={p.name}/><div><p className="label">{state.departments.find(d=>d.id===p.departmentId)?.name}</p><h1 className="text-2xl font-extrabold">{p.name} 교수</h1></div></header><CapacityCard key={p.id} professorId={p.id}/><div role="tablist" aria-label="교수 업무" className="flex gap-2 overflow-auto">{tabs.map(([id,label])=><button role="tab" aria-selected={tab===id} key={id} className={'whitespace-nowrap '+(tab===id?'btn':'btn-alt')} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='applications'&&<section><div className="mb-4 flex items-center justify-between gap-2"><h2 className="section-title">지도 신청 검토</h2><select aria-label="신청 상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 상태</option>{['제출됨','면담 요청','수정 요청','승인','반려'].map(s=><option key={s} value={s}>{s==='제출됨'?'대기':s}</option>)}</select></div><div className="space-y-4">{applications.filter(a=>filter==='all'||a.status===filter).map(a=><ApplicationReview key={a.id+a.status} application={a}/>)}{!applications.filter(a=>filter==='all'||a.status===filter).length&&<p className="card text-sm text-slate-500">검토할 신청이 없습니다.</p>}</div></section>}
 {tab==='meetings'&&<section className="space-y-4"><h2 className="section-title">면담 일정</h2>{state.meetings.filter(m=>m.professorId===p.id).map(m=><article className="card" key={m.id}><b>{state.students.find(s=>s.id===m.studentId)?.name}</b><Badge className="ml-2">{m.status}</Badge><p className="my-3 font-bold">{m.selected?'면담 확정: '+dateLabel(m.selected):'학생의 시간 선택을 기다립니다.'}</p><p className="text-sm">{m.location}</p><details className="my-3"><summary>제안한 시간 보기</summary><div className="mt-3 flex flex-wrap gap-2">{m.slots.map(t=><Badge key={t}>{dateLabel(t)}</Badge>)}</div></details>{m.status==='확정'&&<button className="btn" onClick={()=>state.act({role:'professor',id:p.id},{type:'completeMeeting',id:m.id})}>면담 완료 처리</button>}</article>)}{!state.meetings.some(m=>m.professorId===p.id)&&<p className="card">제안한 면담이 없습니다.</p>}</section>}
 {['plan','final'].includes(tab)&&<section className="space-y-4"><h2 className="section-title">{tab==='plan'?'연구계획서 검토':'최종논문 검토'}</h2>{state.submissions.filter(s=>s.professorId===p.id&&s.kind===tab).slice().reverse().map(s=><SubmissionReview key={s.id+s.status} submission={s}/>)}{!state.submissions.some(s=>s.professorId===p.id&&s.kind===tab)&&<p className="card">제출된 자료가 없습니다.</p>}</section>}
 {tab==='students'&&<section className="grid gap-4 sm:grid-cols-2">{!advisees.length&&<p className="card text-sm text-slate-500 sm:col-span-2">현재 지도 중인 학생이 없습니다. 지도 신청 탭에서 신청을 확인하세요.</p>}{advisees.map(s=><article key={s.id} className="card"><div className="flex items-center gap-3"><Avatar name={s.name}/><div><b>{s.name}</b><div className="mt-2 flex gap-2"><Badge>{s.studentNo}</Badge><Badge>{s.graduationSemester}</Badge></div></div></div><AdviseeActions key={s.id+p.id} studentId={s.id} departmentId={p.departmentId}/></article>)}</section>}
 </div>;
}
function AdviseeActions({studentId,departmentId}:{studentId:string;departmentId:string}) {
 const state=useBoardStore(),student=state.students.find(s=>s.id===studentId)!,d=state.departments.find(d=>d.id===departmentId)!;
 const current=progress(state,student,d).current;
 const form=useSavedForm('advisee-'+studentId+departmentId,{slots:[] as string[],location:'',condition:''});
 const actor={role:'professor' as const,id:state.professorId};
 const conditions=[...new Set(d.stages.flatMap(v=>v.conditionalDeadlines??[]).map(v=>v.condition))];
 return <div className="mt-4 space-y-3"><p className="text-sm">현재 단계: {current?.name??'완료'}</p>{current?.stepType==='MEETING'&&<details><summary className="cursor-pointer font-bold">지도 면담 제안</summary><MeetingGrid value={form.value.slots} onChange={slots=>form.save({...form.value,slots})}/><label className="field-label">지도 면담 장소<input value={form.value.location} onChange={e=>form.save({...form.value,location:e.target.value})}/></label><button className="btn mt-3" onClick={()=>state.act(actor,{type:'proposeMeeting',studentId,departmentId,slots:form.value.slots,location:form.value.location})}>지도 면담 시간 제안</button></details>}{current?.collectsReviewOutcome&&<><label className="field-label">심사 결과<select value={form.value.condition} onChange={e=>form.save({...form.value,condition:e.target.value})}><option value="">결과 선택</option>{conditions.map(v=><option key={v}>{v}</option>)}</select></label><button className="btn" disabled={!form.value.condition} onClick={()=>state.act(actor,{type:'recordOutcome',studentId,departmentId,condition:form.value.condition})}>심사 결과 저장</button></>}{state.reviewOutcomes.filter(r=>r.studentId===studentId&&r.departmentId===departmentId).map(r=><p key={r.at}>심사 결과: {r.condition} · {dateLabel(r.at)}</p>)}</div>;
}
function CapacityCard({professorId}:{professorId:string}){
 const state=useBoardStore(),p=state.professors.find(p=>p.id===professorId)!;
 const form=useSavedForm('capacity-'+p.id,{capacity:p.capacity,year:p.year,available:p.available});
 const [edit,setEdit]=useState(false),count=approvedCount(state,p);
 return <section className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="section-title">{p.year}학년도 지도 정원</h2><Badge className={p.available&&count<p.capacity?'bg-emerald-50':'bg-red-50'}>{p.available&&count<p.capacity?'모집 중':'마감'}</Badge></div><div className="my-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{[['지도 정원',p.capacity],['승인',count],['검토 대기',state.applications.filter(a=>a.professorId===p.id&&!['승인','반려'].includes(a.status)).length],['남은 자리',p.capacity-count]].map(([label,value])=><div className="rounded-xl bg-slate-50 p-3" data-testid={'capacity-'+label} key={label}><p className="label">{label}</p><b className="text-2xl">{value}</b></div>)}</div><button className="btn-alt" onClick={()=>setEdit(!edit)}>정원·모집 수정</button>{edit&&<form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();if(state.act({role:'professor',id:p.id},{type:'capacity',...form.value}))setEdit(false);}}><div className="grid gap-3 sm:grid-cols-3"><label className="field-label">학년도<input type="number" value={form.value.year} onChange={e=>form.save({...form.value,year:Number(e.target.value)})}/></label><label className="field-label">지도 정원<input type="number" value={form.value.capacity} onChange={e=>form.save({...form.value,capacity:Number(e.target.value)})}/></label><label className="field-label">모집 상태<select value={form.value.available?'open':'closed'} onChange={e=>form.save({...form.value,available:e.target.value==='open'})}><option value="open">모집 중</option><option value="closed">마감</option></select></label></div>{form.value.capacity<count&&<p role="alert" className="text-sm text-red-700">현재 승인 {count}명보다 작게 설정할 수 없습니다.</p>}<p className="text-xs">작성 내용 자동 저장</p><button type="button" className="btn-alt mr-2" onClick={()=>form.save(form.value)}>임시저장</button><button className="btn" disabled={form.value.capacity<count}>정원 저장</button></form>}</section>;
}
function ApplicationReview({application:a}:{application:Application}){
 const state=useBoardStore(),student=state.students.find(s=>s.id===a.studentId)!,p=state.professors.find(p=>p.id===a.professorId)!;
 const form=useSavedForm('review-'+a.id,{text:'',slots:[] as string[],location:''});
 const [meeting,setMeeting]=useState(false);
 const actor={role:'professor' as const,id:state.professorId};
 return <article className="card"><div className="flex gap-3"><Avatar name={student.name}/><div><b>{student.name}</b><div className="my-2 flex flex-wrap gap-2"><Badge>{student.graduationSemester} 졸업예정</Badge><Badge>{state.departments.find(d=>d.id===a.departmentId)?.name}</Badge><Badge>{majorRole(student,a.departmentId)==='primary'?'주전공':'복수전공'}</Badge><Badge>{a.status}</Badge><Badge>{dateLabel(a.requestedAt)}</Badge></div></div></div><h3 className="mt-2 font-bold">{a.title}</h3><p className="mt-1 text-sm text-slate-500">{a.summary}</p><details className="mt-4"><summary className="cursor-pointer font-bold">신청 상세 보기</summary><p className="my-3 whitespace-pre-wrap text-sm">{a.body}</p><FileView file={a.file}/><Badge>{a.meetingWanted?'면담 희망':'면담 희망 없음'}</Badge></details><FeedbackEditor target="application" id={a.id} value={a.feedback}/>
 {!['승인','반려'].includes(a.status)&&<div className="mt-4 space-y-3"><label className="field-label">처리 피드백<textarea value={form.value.text} onChange={e=>form.save({...form.value,text:e.target.value})}/></label><div className="flex flex-wrap gap-2"><button className="btn" disabled={approvedCount(state,p)>=p.capacity} onClick={()=>state.act(actor,{type:'decide',id:a.id,status:'승인',feedback:form.value.text})}>신청 승인</button><button className="btn-alt" onClick={()=>state.act(actor,{type:'decide',id:a.id,status:'수정 요청',feedback:form.value.text})}>수정 요청</button><button className="btn-alt" onClick={()=>setMeeting(!meeting)}>면담 요청</button><button className="btn-alt" onClick={()=>state.act(actor,{type:'decide',id:a.id,status:'반려',feedback:form.value.text})}>반려</button><button className="btn-alt" onClick={()=>form.save(form.value)}>임시저장</button></div>{approvedCount(state,p)>=p.capacity&&<p className="text-xs text-red-700">정원 마감으로 승인할 수 없습니다.</p>}{meeting&&<div className="rounded-xl border p-3"><MeetingGrid value={form.value.slots} onChange={slots=>form.save({...form.value,slots})}/><label className="field-label mt-3">면담 장소 또는 온라인 링크<input value={form.value.location} onChange={e=>form.save({...form.value,location:e.target.value})}/></label><button className="btn mt-3" onClick={()=>state.act(actor,{type:'decide',id:a.id,status:'면담 요청',feedback:form.value.text,slots:form.value.slots,location:form.value.location})}>면담 시간 제안 보내기</button></div>}</div>}</article>;
}
function FeedbackEditor({target,id,value}:{target:'application'|'submission';id:string;value?:Application['feedback']}){
 const state=useBoardStore(),[edit,setEdit]=useState(false);
 const form=useSavedForm('feedback-'+target+id,{text:value?.text??''});
 if(!value)return null;
 return <div><FeedbackView value={value}/><button className="btn-alt mt-2" onClick={()=>setEdit(!edit)}>피드백 수정</button>{edit&&<div className="mt-3 space-y-2"><label className="field-label">수정할 피드백<textarea value={form.value.text} onChange={e=>form.save({text:e.target.value})}/></label><button className="btn-alt mr-2" onClick={()=>form.save(form.value)}>임시저장</button><button className="btn" onClick={()=>{if(state.act({role:'professor',id:state.professorId},{type:'editFeedback',target,id,text:form.value.text}))setEdit(false);}}>피드백 수정 저장</button></div>}{value.history.length>0&&<details className="mt-2 text-xs text-slate-500"><summary>이전 피드백 이력</summary>{value.history.map((v,i)=><p key={i}>{dateLabel(v.at)} · {v.text}</p>)}</details>}</div>;
}
function SubmissionReview({submission:s}:{submission:Submission}){
 const state=useBoardStore(),student=state.students.find(st=>st.id===s.studentId)!;
 const form=useSavedForm('submission-feedback-'+s.id,{text:''});
 return <article className="card"><div className="flex items-center gap-3"><Avatar name={student.name}/><b>{student.name}</b><Badge>v{s.version}</Badge><Badge>{s.status}</Badge></div><Badge className="my-3">{dateLabel(s.submittedAt)}</Badge><div className="my-2 flex flex-wrap gap-2"><StageBadges step={state.departments.find(d=>d.id===s.departmentId)!.stages.find(v=>v.id===s.stageId)!}/></div><h3 className="font-bold">{s.title}</h3><p className="my-3 whitespace-pre-wrap text-sm">{s.body}</p>{s.videoUrl&&<p className="break-all text-sm">영상 링크 기록: {s.videoUrl}</p>}<FileView file={s.file}/><FeedbackEditor target="submission" id={s.id} value={s.feedback}/>{s.status==='제출됨'&&<><label className="field-label mt-4">검토 피드백<textarea value={form.value.text} onChange={e=>form.save({text:e.target.value})}/></label><div className="mt-3 flex flex-wrap gap-2"><button className="btn" onClick={()=>state.act({role:'professor',id:state.professorId},{type:'review',id:s.id,status:'승인',feedback:form.value.text})}>제출물 승인</button><button className="btn-alt" onClick={()=>state.act({role:'professor',id:state.professorId},{type:'review',id:s.id,status:'수정 요청',feedback:form.value.text})}>제출물 수정 요청</button><button className="btn-alt" onClick={()=>form.save(form.value)}>임시저장</button></div></>}</article>;
}
