import type {Stage,StepType} from '@/lib/types';
import {stepKinds} from '@/data/departments/reference';
import {Badge} from './ui';
export const stepTypeLabels:Record<StepType,string>={APPLICATION:'신청서·개요 기록',ADVISOR_REQUEST:'지도교수 신청·승인',COURSE_ENROLLMENT:'외부 수강·분반 확인',PLAN_SUBMISSION:'연구계획서 제출',MEETING:'지도교수 면담',CHECKPOINT:'교수 중간점검',PRESENTATION:'발표회·영상 제출',FINAL_SUBMISSION:'최종논문 제출',EXTERNAL_SUBMISSION:'외부 제출 자가 체크'};
export function StageFields({step:s,onChange}:{step:Stage;onChange:(v:Partial<Stage>)=>void}) {
 return <div className="space-y-3 rounded-lg bg-slate-50 p-3 sm:col-span-2">
  <div className="grid gap-3 sm:grid-cols-2"><label className="field-label">단계 유형 (stepType)<select value={s.stepType??'EXTERNAL_SUBMISSION'} onChange={e=>{const stepType=e.target.value as StepType;onChange({stepType,kind:stepKinds[stepType],collectsReviewOutcome:false,requiresVideo:false,approver:['APPLICATION','EXTERNAL_SUBMISSION'].includes(stepType)?'NONE':['COURSE_ENROLLMENT','PRESENTATION'].includes(stepType)?'EXTERNAL':'ADVISOR',submitTo:['COURSE_ENROLLMENT','PRESENTATION'].includes(stepType)?'OTHER':stepType==='EXTERNAL_SUBMISSION'?'DEPT_OFFICE':'IN_SERVICE'});}}>{Object.entries(stepTypeLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
  <label className="field-label">완료 판정 주체<select value={s.approver??'NONE'} onChange={e=>onChange({approver:e.target.value as Stage['approver']})}><option value="ADVISOR">지도교수</option><option value="NONE">서비스 기록·자가 체크</option><option value="EXTERNAL">외부 절차</option></select></label>
  <label className="field-label">제출처 구분<select value={s.submitTo??'OTHER'} onChange={e=>{const submitTo=e.target.value as Stage['submitTo'];onChange({submitTo,submissionMethod:({IN_SERVICE:'서비스 내 제출',DEPT_OFFICE:'학과사무실',EMAIL:'이메일',OTHER:'외부 절차'})[submitTo!],...(s.stepType==='PRESENTATION'?{kind:submitTo==='IN_SERVICE'?'plan':'task',approver:submitTo==='IN_SERVICE'?'NONE':'EXTERNAL',requiresVideo:submitTo==='IN_SERVICE'}:{})});}}><option value="IN_SERVICE">서비스 제출</option><option value="DEPT_OFFICE">학과사무실</option><option value="EMAIL">이메일</option><option value="OTHER">외부 절차</option></select></label>
  <label className="field-label">날짜 근거<select value={s.dateStatus??'PLACEHOLDER'} onChange={e=>onChange({dateStatus:e.target.value as Stage['dateStatus'],isPlaceholder:e.target.value==='PLACEHOLDER'})}><option value="CONFIRMED">자료에서 확인된 날짜</option><option value="PLACEHOLDER">데모 가정</option></select></label></div>
  {s.dateStatus==='PLACEHOLDER'&&<Badge>예정값</Badge>}
  <label className="flex gap-2 text-sm"><input type="checkbox" checked={s.attendanceRequired??false} onChange={e=>onChange({attendanceRequired:e.target.checked})}/>필참 여부</label>
  <label className="flex gap-2 text-sm"><input type="checkbox" checked={s.requiresAdvisorSignature??false} onChange={e=>onChange({requiresAdvisorSignature:e.target.checked})}/>지도교수 서명 필요</label>
  {s.stepType==='CHECKPOINT'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={s.collectsReviewOutcome??false} onChange={e=>onChange({collectsReviewOutcome:e.target.checked,kind:e.target.checked?'task':'plan'})}/>교수 심사 결과 입력 단계</label>}
  {s.stepType==='FINAL_SUBMISSION'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={s.requiresVideo??false} onChange={e=>onChange({requiresVideo:e.target.checked})}/>영상 링크 함께 제출</label>}
  <label className="field-label">미이행 영향<input value={s.consequence??''} onChange={e=>onChange({consequence:e.target.value})}/></label>
  <label className="field-label">규정·제약 (줄별 입력)<textarea value={s.constraints?.join('\n')??''} onChange={e=>onChange({constraints:e.target.value.split('\n')})}/></label>
  <label className="field-label">일정 근거 설명<input value={s.dateNote??''} onChange={e=>onChange({dateNote:e.target.value})}/></label>
  <fieldset className="space-y-2"><legend className="field-label">조건부 마감</legend>{(s.conditionalDeadlines??[]).map((v,i)=><div key={i} className="grid gap-2"><label className="field-label">조건 {i+1}<input value={v.condition} onChange={e=>onChange({conditionalDeadlines:s.conditionalDeadlines!.map((r,j)=>j===i?{...r,condition:e.target.value}:r)})}/></label><label className="field-label">조건 마감 {i+1}<input type="datetime-local" value={v.deadline} onChange={e=>onChange({conditionalDeadlines:s.conditionalDeadlines!.map((r,j)=>j===i?{...r,deadline:e.target.value}:r)})}/></label><button className="btn-alt" onClick={()=>onChange({conditionalDeadlines:s.conditionalDeadlines!.filter((_,j)=>j!==i)})}>조건 {i+1} 삭제</button></div>)}<button className="btn-alt" onClick={()=>onChange({conditionalDeadlines:[...(s.conditionalDeadlines??[]),{condition:'',deadline:''}]})}>조건부 마감 추가</button></fieldset>
 </div>;
}
