"use client";
import {useEffect,useRef,useState} from 'react';
import {useBoardStore} from '@/lib/store';
import {advisorFor,applicationFor,approvedCount,canApply,dday,deadlinesFor,duplicateSubmission,draftKey,emptyDraft,latestSubmission,noticeMatches,progress,stagesFor} from '@/lib/rules';
import type {Application,Department,Draft,Student} from '@/lib/types';
import {Avatar,Badge,colorFor,dateLabel,FeedbackView,FileInput,FileView,OfficialLink} from './ui';
import {Roadmap} from './roadmap';
import {Calendar} from './calendar';
import {MeetingGrid} from './meeting-grid';
import {StudentTabs,StudentPanel,areaForTarget,type StudentArea} from './student-tabs';

import {StageDeadlines} from './stage-metadata';
export function StudentBoard(){
 const state=useBoardStore(),student=state.students.find(s=>s.id===state.studentId)!;
 const [tab,setTab]=useState(''),[target,setTarget]=useState(''),[area,setArea]=useState<StudentArea>('roadmap');
 const lastStudent=useRef(student.id);
 const chooseArea=(id:StudentArea)=>{setArea(id);const url=new URL(window.location.href);url.hash=id;window.history.replaceState(null,'',url);};
 const navigate=(dept:string,destination:string)=>{setTab(dept);setArea(areaForTarget(destination));setTarget(destination);const url=new URL(window.location.href);url.searchParams.set('department',dept);url.hash=destination;window.history.replaceState(null,'',url);};
 const departments=state.departments.filter(d=>student.majors.some(m=>m.departmentId===d.id));
 const d=departments.find(d=>d.id===tab)??departments[0];
 useEffect(()=>{const update=()=>{const id=new URLSearchParams(window.location.search).get('department');if(id)setTab(id);const destination=window.location.hash.slice(1);setArea(areaForTarget(destination));if(destination)setTarget(destination);};update();window.addEventListener('popstate',update);window.addEventListener('hashchange',update);return()=>{window.removeEventListener('popstate',update);window.removeEventListener('hashchange',update);};},[]);
 useEffect(()=>{if(lastStudent.current!==student.id){lastStudent.current=student.id;setTab('');setArea('roadmap');setTarget('');const url=new URL(window.location.href);url.searchParams.delete('department');url.hash='';window.history.replaceState(null,'',url);}},[student.id]);
 useEffect(()=>{if(target){const el=document.getElementById(target);const detail=el?.querySelector('details');if(detail&&target.startsWith('step-'))detail.open=true;el?.scrollIntoView({behavior:'smooth',block:'center'});setTarget('');}},[target,tab,area]);
 if(!d)return <p>전공 정보 확인 필요</p>;
 const pr=progress(state,student,d),app=applicationFor(state,student.id,d.id),advisor=advisorFor(state,student,d),now=new Date().toISOString();
 const actor={role:'student' as const,id:student.id};
 const meeting=state.meetings.find(m=>m.studentId===student.id&&m.departmentId===d.id&&m.status==='시간 제안됨');
 const current=pr.current,sub=current&&latestSubmission(state,student.id,d.id,current.id);
 const waiting=app?.status==='제출됨'&&['application','approval'].includes(current?.kind??'') || sub?.status==='제출됨';
 const action=meeting?'면담 시간 고르기':current?.stepType==='APPLICATION'?'신청서 작성':current?.requiresVideo?'제출 자료 작성':current?.kind==='plan'?'연구계획 작성':current?.kind==='final'?'최종논문 제출':current?.stepType==='MEETING'?'면담 일정 보기':current?.kind==='course'?'수강 정보 확인':['application','approval'].includes(current?.kind??'')?(app?'신청 현황 보기':'지도교수 찾아 신청하기'):'진행 내용 확인';
 const destination=meeting||current?.stepType==='MEETING'?'meetings':['application','approval'].includes(current?.kind??'')?'advisor':['plan','final'].includes(current?.kind??'')?'documents':'step-action';
 const role=student.majors.find(m=>m.departmentId===d.id)!.role,requirement=d.requirements?.[role];
 return <div className="student-board space-y-3">
  <header className="flex flex-wrap items-center gap-3 rounded-2xl border-l-4 border-snu bg-white p-3"><Avatar name={student.name}/><div><p className="label">학생 · 내 논문 여정</p><h1 className="text-xl font-extrabold">{student.name}</h1></div><Badge>{student.studentNo}</Badge><Badge>{student.graduationSemester} 졸업예정</Badge>{student.registeredSemesters>8&&<Badge className="bg-amber-50">초과학기</Badge>}</header>
  {departments.length>1?<section aria-label="내 전공 요약" className="grid grid-cols-2 gap-2">{departments.map(dept=>{const p=progress(state,student,dept),percent=p.steps.length?Math.round(p.completed/p.steps.length*100):0;const major=student.majors.find(m=>m.departmentId===dept.id)!;return <button aria-label={dept.name+' 전공 선택'} aria-describedby={'major-progress-'+dept.id} aria-pressed={d.id===dept.id} className={'min-w-0 rounded-xl border p-3 text-left text-snu transition '+(d.id===dept.id?'border-snu bg-snu-100 shadow-sm':'border-snu-300 bg-white hover:bg-snu-50')} key={dept.id} onClick={()=>{setTab(dept.id);const url=new URL(window.location.href);url.searchParams.set('department',dept.id);url.hash=area;window.history.replaceState(null,'',url);}}><span className="flex flex-wrap items-center gap-1 text-sm font-bold"><span aria-hidden="true" className={'h-2 w-2 rounded-full '+colorFor(dept)}/>{dept.name}<span className="text-xs font-normal">{major.role==='primary'?'주전공':'복수전공'}</span></span>{dept.requirements?.[major.role]==='필수'?<><span id={'major-progress-'+dept.id} className="mt-2 block text-xs leading-relaxed">진행률 {percent}% · {p.steps.length}단계 중 {p.completed}단계 완료</span><span data-testid="major-progress-track" className="my-2 block h-1.5 overflow-hidden rounded-full bg-slate-200" aria-hidden="true"><span className="block h-full rounded-full bg-snu" style={{width:percent+'%'}}/></span><span className="block text-xs">{p.current?dday(deadlinesFor(state,student.id,dept,p.current).map(v=>v.deadline).sort()[0]??'',now):'모든 단계 완료'}</span></>:<span id={'major-progress-'+dept.id} className="mt-2 block text-xs">{dept.requirements?.[major.role]==='면제'?'논문 면제':'논문 요건 정보 확인 필요'}</span>}</button>;})}</section>:<h2 className="text-lg font-bold text-snu">{d.name}</h2>}
  <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><span>{d.semester}</span><span>· {d.method==='course'?'수업형':'신청·승인형'}</span><OfficialLink value={d.officialLink}/></div>
  <StudentTabs value={area} onChange={chooseArea}/>
  {!requirement?<p role="alert" className="card">논문 요건 정보 확인 필요</p>:requirement==='면제'?<p className="card">{d.name} 논문 면제</p>:<>
   <section className="student-next-action rounded-2xl border border-snu bg-snu px-4 py-3 text-white shadow-sm" aria-label="다음 할 일"><div className="flex flex-wrap items-center justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-bold">다음 할 일 · {d.name}</p><h2 className="mt-1 text-lg font-extrabold">{meeting?'면담 시간 선택':waiting?'교수 검토 중':current?.name??'모든 단계 완료'}</h2>{current&&<div className="mt-2 flex flex-wrap gap-1"><StageDeadlines state={state} studentId={student.id} department={d} step={current}/><Badge>{dday(deadlinesFor(state,student.id,d,current).map(v=>v.deadline).sort()[0]??'',now)}</Badge>{current.requiresAdvisorSignature&&<Badge>지도교수 서명 필요</Badge>}</div>}{waiting&&<p className="mt-2 text-xs">검토 결과는 알림으로 알려드립니다.</p>}</div>{current&&<button className="student-next-button shrink-0 rounded-lg bg-white px-3 py-2 text-sm font-bold text-snu hover:bg-snu-100" onClick={()=>navigate(d.id,destination)}>{action}</button>}</div></section>
   <StudentPanel id="roadmap" active={area}><section id="roadmap" className="card"><h2 className="section-title mb-3">전공 로드맵</h2>{area==='roadmap'&&<Roadmap key={student.id+d.id} state={state} student={student} department={d}/>}</section>
   {current?.kind==='course'&&<section id="step-action" className="card"><h2 className="section-title">수강 정보 확인</h2><p className="mt-3 text-sm">수강 분반은 외부 수강 데이터로 확인합니다. 서비스에서 수강신청하거나 교수를 배정하지 않습니다.</p><p>분반 정보 확인 필요: 학과 수강 담당자에게 문의하세요.</p></section>}
   {current?.kind==='task'&&current.stepType!=='MEETING'&&<section id="step-action" className="card"><h2 className="section-title">{current.name}</h2><p className="my-3 text-sm text-slate-500">안내된 활동을 마친 뒤 완료를 기록하세요.</p>{current.approver==='ADVISOR'?<p>지도교수의 확인을 기다립니다.</p>:<button className="btn" onClick={()=>state.act(actor,{type:'completeStep',departmentId:d.id,stageId:current.id})}>{current.stepType==='EXTERNAL_SUBMISSION'?'제출 완료 체크':'단계 완료 기록'}</button>}</section>}
   </StudentPanel>
   <StudentPanel id="advisor" active={area}><section className="card scroll-mt-6" id="advisor"><h2 className="section-title">지도교수</h2>{d.method==='course'?<div className="mt-4"><Badge className="bg-sky-50">수강 분반 교수</Badge><p className="my-3 font-bold">{advisor?advisor.name+' 교수':'수강 분반 정보 확인 필요'}</p>{state.sections.filter(c=>student.enrollmentIds.includes(c.id)&&c.departmentId===d.id).map(c=><p className="text-sm text-slate-500" key={c.id}>{c.name}</p>)}</div>:<ApplicationPanel key={student.id+d.id+(app?.status??'new')} student={student} department={d} application={app}/>}</section></StudentPanel>
   <StudentPanel id="meetings" active={area}><StudentMeetings key={student.id+d.id} student={student} department={d}/></StudentPanel>
   <StudentPanel id="documents" active={area}><section id="documents" className="card"><h2 className="section-title">연구계획서 · 논문</h2>{current&&['plan','final'].includes(current.kind)?<SubmissionForm key={student.id+d.id+current.id+(sub?.status??'new')} student={student} department={d} stageId={current.id}/>:<p className="my-3 text-sm text-slate-500">해당 제출 단계에 도달하면 작성할 수 있습니다.</p>}{state.submissions.filter(s=>s.studentId===student.id&&s.departmentId===d.id).slice().reverse().map(s=><div key={s.id} className="mt-4 rounded-xl border p-3"><div className="flex flex-wrap gap-2"><b>{d.stages.find(v=>v.id===s.stageId)?.name??'제출물'}</b><Badge>v{s.version}</Badge><Badge>{s.status}</Badge><Badge>{dateLabel(s.submittedAt)}</Badge></div>{s.videoUrl&&<p className="break-all text-sm">영상 링크 기록: {s.videoUrl}</p>}<FileView file={s.file}/><FeedbackView value={s.feedback}/></div>)}</section></StudentPanel>
  </>}
  <StudentPanel id="notices" active={area}><section id="notices" className="card"><h2 className="section-title">내 전공 공지</h2>{state.notices.filter(n=>noticeMatches(n,student,d)).map(n=><article className="mt-4 rounded-xl border p-4" key={n.id}><Badge>{n.semester}</Badge><h3 className="mt-2 font-bold">{n.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm">{n.body}</p><FileView file={n.file}/></article>)}{!state.notices.some(n=>noticeMatches(n,student,d))&&<p className="mt-3 text-sm text-slate-500">새 공지가 없습니다.</p>}</section></StudentPanel>
  <StudentPanel id="calendar" active={area}><Calendar key={student.id} state={state} student={student} onSelect={navigate}/></StudentPanel>
 </div>;
}

function ApplicationPanel({student,department:d,application:app}:{student:Student;department:Department;application?:Application}){
 const state=useBoardStore(),actor={role:'student' as const,id:student.id};
 const persisted=state.drafts.find(v=>v.id===draftKey(student.id,d.id,'application'));
 const initial=persisted??(app&&app.status==='수정 요청'?{...app,savedAt:''}:emptyDraft(student.id,d.id,'application'));
 const [draft,setDraft]=useState<Draft>(initial),[saved,setSaved]=useState('');
 const [college,setCollege]=useState(d.college),[dept,setDept]=useState(d.id),[field,setField]=useState(''),[query,setQuery]=useState('');
 const editable=!app||['수정 요청','반려'].includes(app.status);
 const update=(patch:Partial<Draft>)=>{const next={...draft,...patch};setDraft(next);state.act(actor,{type:'saveDraft',draft:next});};
 const currentDraft=state.drafts.find(v=>v.id===draftKey(student.id,d.id,'application'));
 return <div className="mt-4">{app&&<div className="mb-4 rounded-xl border p-4"><div className="flex flex-wrap gap-2"><b>{state.professors.find(p=>p.id===app.professorId)?.name} 교수</b><Badge>{app.status}</Badge><Badge>{dateLabel(app.requestedAt)}</Badge></div><p className="mt-3 font-bold">{app.title}</p><p className="text-sm text-slate-500">{app.summary}</p><FeedbackView value={app.feedback}/>{!editable&&<details className="mt-3"><summary>제출한 신청서 (읽기 전용)</summary><p className="mt-3 whitespace-pre-wrap text-sm">{app.body}</p><FileView file={app.file}/><Badge>{app.meetingWanted?'면담 희망':'면담 희망 없음'}</Badge></details>}</div>}
 {editable&&<><h3 className="font-bold">교수 탐색</h3><div className="my-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="field-label">단과대학<select value={college} onChange={e=>setCollege(e.target.value)}><option value="">전체</option>{[...new Set(state.departments.map(d=>d.college))].map(c=><option key={c}>{c}</option>)}</select></label><label className="field-label">학과<select value={dept} onChange={e=>setDept(e.target.value)}><option value="">전체</option>{state.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="field-label">연구분야<input value={field} onChange={e=>setField(e.target.value)} placeholder="예: 인지심리"/></label><label className="field-label">키워드 검색<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 기억"/></label></div>
 <div className="grid gap-3 md:grid-cols-2">{state.professors.filter(p=>(!dept||p.departmentId===dept)&&(!college||state.departments.find(d=>d.id===p.departmentId)?.college===college)&&p.field.includes(field)&&[p.name,...p.keywords,p.topics].join(' ').includes(query)).map(p=>{const available=canApply(state,p),same=p.departmentId===d.id;return <article className="rounded-xl border p-4" key={p.id}><div className="flex items-center gap-3"><Avatar name={p.name}/><div><h4 className="font-bold">{p.name} 교수</h4><p className="text-xs text-slate-500">{state.departments.find(d=>d.id===p.departmentId)?.name} · {p.field}</p></div></div><div className="my-3 flex flex-wrap gap-2">{p.keywords.map(k=><Badge key={k}>{k}</Badge>)}<Badge className={available?'bg-emerald-50':'bg-red-50'}>{available?'여석 '+(p.capacity-approvedCount(state,p)):'정원 마감'}</Badge></div><p className="mb-2 text-xs">{p.contact}</p><OfficialLink value={p.labLink}/><button className="btn mt-3 block w-full" disabled={!available||!same||app?.status==='수정 요청'&&app.professorId!==p.id} onClick={()=>update({professorId:p.id})}>{draft.professorId===p.id?'선택됨':p.name+' 교수 선택'}</button>{!available&&<p className="mt-2 text-xs text-red-700">정원 마감 또는 모집 종료로 신청할 수 없습니다.</p>}{!same&&<p className="text-xs">현재 전공의 교수를 선택하세요.</p>}</article>;})}</div>
 <form className="mt-5 space-y-4" onSubmit={e=>{e.preventDefault();state.act(actor,{type:'sendApplication',draft});}}><h3 className="font-bold">지도 신청서</h3><p className="text-xs text-slate-500">자동 저장 · {currentDraft?.savedAt?dateLabel(currentDraft.savedAt):'아직 저장하지 않음'} {saved}</p><label className="field-label">연구 제목<input value={draft.title} onChange={e=>update({title:e.target.value})}/></label><label className="field-label">연구 방향 요약<input value={draft.summary} onChange={e=>update({summary:e.target.value})}/></label><label className="field-label">연구계획 본문<textarea rows={5} value={draft.body} onChange={e=>update({body:e.target.value})}/></label><FileInput value={draft.file} onChange={file=>update({file})} label="연구계획 파일"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.meetingWanted} onChange={e=>update({meetingWanted:e.target.checked})}/>면담 희망</label><p className="text-xs text-slate-500">본문 또는 파일 중 하나 이상을 작성하세요. 신청이 첫 연락이 됩니다.</p><div className="flex flex-wrap gap-2"><button className="btn-alt" type="button" onClick={()=>{if(state.act(actor,{type:'saveDraft',draft}))setSaved('저장 완료');}}>임시저장</button><button className="btn" disabled={!draft.professorId}>{app?.status==='수정 요청'?'재제출':'지도 신청 제출'}</button></div></form></>}
 </div>;
}
function StudentMeetings({student,department:d}:{student:Student;department:Department}){
 const state=useBoardStore(),[selection,setSelection]=useState<Record<string,string[]>>({});
 const meetings=state.meetings.filter(m=>m.studentId===student.id&&m.departmentId===d.id);
 if(!meetings.length)return <section id="meetings" className="card"><h2 className="section-title">면담 일정</h2><p className="mt-3 text-sm text-slate-500">아직 제안된 면담이 없습니다. 교수가 시간을 제안하면 여기에서 선택할 수 있습니다.</p></section>;
 return <section id="meetings" className="card"><h2 className="section-title">면담 일정</h2>{meetings.map(m=><div className="mt-3" key={m.id}><Badge>{m.status}</Badge>{m.selected&&<p className="my-3 font-bold">면담 확정: {dateLabel(m.selected)}</p>}<p className="my-2 text-sm">{m.location||'장소는 교수와 확인해 주세요.'}</p>{m.status==='시간 제안됨'&&<><MeetingGrid allowed={m.slots} value={selection[m.id]??[]} onChange={v=>setSelection({...selection,[m.id]:v})}/><button className="btn mt-3" disabled={!selection[m.id]?.length} onClick={()=>state.act({role:'student',id:student.id},{type:'selectSlot',id:m.id,slot:selection[m.id][0]})}>선택 시간 확정</button></>}</div>)}</section>;
}
function SubmissionForm({student,department:d,stageId}:{student:Student;department:Department;stageId:string}){
 const state=useBoardStore(),existing=latestSubmission(state,student.id,d.id,stageId),actor={role:'student' as const,id:student.id};
 const [draft,setDraft]=useState<Draft>(state.drafts.find(v=>v.id===draftKey(student.id,d.id,stageId))??{...emptyDraft(student.id,d.id,stageId),title:existing?.title??'',body:existing?.body??''});
 const [saved,setSaved]=useState(false);
 const step=d.stages.find(v=>v.id===stageId)!;
 const duplicate=step.kind==='final'&&duplicateSubmission(state,draft);
 const editable=!existing||existing.status==='수정 요청';
 const update=(patch:Partial<Draft>)=>{const v={...draft,...patch,...('file' in patch?{duplicateAcknowledged:false}:{})};setDraft(v);state.act(actor,{type:'saveDraft',draft:v});};
 if(!editable)return <p className="my-4 text-sm">제출 완료 · 교수 검토 중 (읽기 전용)</p>;
 return <form className="mt-4 space-y-4" onSubmit={e=>{e.preventDefault();state.act(actor,{type:'sendSubmission',draft});}}><p className="text-xs text-slate-500">자동 저장 · {dateLabel(state.drafts.find(v=>v.id===draftKey(student.id,d.id,stageId))?.savedAt??'')}{saved&&' · 저장 완료'}</p><label className="field-label">제출물 제목<input value={draft.title} onChange={e=>update({title:e.target.value})}/></label><label className="field-label">제출물 본문<textarea value={draft.body} rows={5} onChange={e=>update({body:e.target.value})}/></label>{step.constraints?.map(c=><p role="note" className="rounded bg-amber-50 p-3 text-sm" key={c}>{c}</p>)}{step.requiresVideo&&<label className="field-label">영상 제출 링크<input type="url" value={draft.videoUrl??''} onChange={e=>update({videoUrl:e.target.value})}/><span className="text-xs">HTTPS 링크만 기록합니다. 실제 영상 업로드·이메일 제출을 대신하지 않습니다.</span></label>}<FileInput value={draft.file} onChange={file=>update({file})} label="제출 파일"/>{duplicate&&<div role="alert" className="rounded bg-amber-50 p-3 text-sm">다른 전공에 동일한 파일을 제출한 기록이 있습니다. 이중 제출 규정을 확인하세요.<label className="mt-2 flex gap-2"><input type="checkbox" checked={draft.duplicateAcknowledged??false} onChange={e=>update({duplicateAcknowledged:e.target.checked})}/>경고 확인 (실제 제출 허용을 의미하지 않음)</label></div>}<div className="flex gap-2"><button type="button" className="btn-alt" onClick={()=>setSaved(state.act(actor,{type:'saveDraft',draft}))}>임시저장</button><button className="btn">{existing?'제출물 재제출':'제출물 제출'}</button></div></form>;
}
