"use client";
import { departments, getDepartment } from "@/data/departments";
import { demoStudentId } from "@/data/seed";
import { canApply, hasSameWeekConflict, nextTask, requiredRoadmaps, stageForApplication } from "@/lib/rules";
import { useBoardStore } from "@/lib/store";
import type { Role } from "@/lib/types";
import { useState } from "react";
const methodText = { contact_approval: "직접 컨택 후 승인", application: "시스템 신청", course_assigned: "수업에서 배정" };
export function StudentBoard() { const state = useBoardStore(); const student = state.students.find((item) => item.id === demoStudentId)!; const [draft, setDraft] = useState<{ primary?: string; secondary?: string }>({}); const maps = requiredRoadmaps(student, departments); const next = nextTask(student, departments, state.applications); const conflict = hasSameWeekConflict(student, departments, state.applications);
 if (!student.selectedMajors.length) return <section className="mx-auto max-w-2xl"><p className="label">학생 시작 설정</p><h1 className="mt-2 text-3xl font-extrabold">전공별 논문 로드맵을 만들어요</h1><p className="mt-3 text-slate-600">가상 학생 {student.name}님의 주전공과 복수전공을 선택하면, 필수 요건인 전공별 절차가 생성됩니다.</p><div className="card mt-7 space-y-5"><MajorSelect label="주전공" value={draft.primary} onChange={(id) => setDraft({ ...draft, primary: id })} /><MajorSelect label="복수전공" value={draft.secondary} onChange={(id) => setDraft({ ...draft, secondary: id })} /><button className="btn" disabled={!draft.primary || !draft.secondary} onClick={() => state.selectMajors([{ departmentId: draft.primary!, role: "primary" }, { departmentId: draft.secondary!, role: "secondary" }])}>전공별 로드맵 생성</button><p className="text-xs text-slate-500">대표 시연 조합을 선택하면 승인부터 확정 검토까지의 흐름을 볼 수 있습니다.</p></div></section>;
 return <div className="space-y-6"><section className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="label">학생 · {student.studentNo}</p><h1 className="mt-1 text-3xl font-extrabold">{student.name}님의 졸업논문 보드</h1><p className="mt-2 text-slate-600">{student.graduationSemester} 졸업 예정 · 졸업논문 대상</p></div><span className="badge h-fit bg-emerald-100 text-emerald-700">정상 진행 중</span></section>{next && <section className="rounded-2xl bg-slate-900 p-6 text-white"><p className="text-sm font-bold text-indigo-200">다음 할 일 · {next.department.name}</p><h2 className="mt-2 text-2xl font-extrabold">{next.stage.name}</h2><p className="mt-2 text-slate-300">{next.stage.description}</p><p className="mt-4 font-bold">마감: {next.stage.dueDate} · {next.stage.submissionMethod} 제출</p></section>}{conflict && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 font-bold text-amber-800">전공별 마감이 같은 주에 겹칩니다. 미리 일정을 조정하세요.</div>}<section className="grid gap-4 lg:grid-cols-2">{maps.map(({ department, role }) => { const app = state.applications.find((item) => item.studentId === student.id && item.departmentId === department.id); const index = stageForApplication(app); return <article className="card" key={department.id}><div className="flex items-start justify-between"><div><p className="label">{role === "primary" ? "주전공" : "복수전공"}</p><h2 className="mt-1 text-xl font-extrabold">{department.name}</h2></div><span className="badge bg-violet-100 text-violet-700">예시 데이터</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="지도교수 방식" value={methodText[department.method]} /><Info label="다음 마감" value={department.stages[index].dueDate} /><Info label="제출 방법" value={department.stages[index].submissionMethod} /><Info label="공식 링크" value={department.officialLink} /></div><div className="mt-5 space-y-2">{department.stages.map((stage, stageIndex) => <div key={stage.id} className={`rounded-lg p-3 text-sm ${stageIndex < index ? "bg-emerald-50 text-emerald-700" : stageIndex === index ? "bg-indigo-50 font-bold text-indigo-800" : "bg-slate-50 text-slate-500"}`}>{stageIndex + 1}. {stage.name}<span className="float-right">{stageIndex < index ? "완료" : stageIndex === index ? "진행 필요" : "예정"}</span></div>)}</div><ApplicationPanel departmentId={department.id} application={app} /></article> })}</section><section className="card"><h2 className="text-xl font-extrabold">전공 통합 마감 캘린더</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{maps.flatMap(({ department }) => department.stages.map((stage) => <div className="rounded-xl bg-slate-50 p-4" key={`${department.id}-${stage.id}`}><span className="badge bg-slate-200 text-slate-700">{department.name}</span><p className="mt-2 font-bold">{stage.dueDate} · {stage.name}</p><p className="text-sm text-slate-500">{stage.documents} / {stage.submissionMethod}</p></div>))}</div></section></div>; }
function MajorSelect({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) { return <label className="block font-bold">{label}<select className="mt-2 w-full rounded-xl border border-slate-300 bg-white p-3" value={value ?? ""} onChange={(event) => onChange(event.target.value)}><option value="">선택하세요</option>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select></label>; }
function Info({ label, value }: { label: string; value: string }) { return <div><p className="label">{label}</p><p className="mt-1 font-bold">{value || "정보 확인 필요"}</p></div>; }
function ApplicationPanel({ departmentId, application }: { departmentId: string; application?: { professorId: string; status: string; feedback?: string; adminReview: string } }) { const state = useBoardStore(); const department = getDepartment(departmentId)!; const professors = state.professors.filter((professor) => professor.departmentId === departmentId); if (department.method === "course_assigned") return <div className="mt-5 rounded-xl bg-sky-50 p-4 text-sm text-sky-800">행정실이 수업 기반으로 배정합니다. 학생 신청은 필요 없습니다.</div>; if (application) return <div className="mt-5 rounded-xl bg-slate-100 p-4 text-sm"><b>신청 상태: {application.status}</b><p className="mt-1">행정실 검토: {application.adminReview}</p>{application.feedback && <p className="mt-2 text-rose-700">피드백: {application.feedback}</p>}</div>; return <div className="mt-5"><p className="mb-2 text-sm font-bold">지도교수 {department.method === "contact_approval" ? "승인 요청" : "신청"}</p><div className="space-y-2">{professors.map((professor) => { const enabled = canApply(department, professor); return <div className="flex items-center justify-between rounded-xl border p-3" key={professor.id}><span className="text-sm"><b>{professor.name}</b> · {professor.keywords.join(", ")} {department.usesCapacity && <em className="ml-1 not-italic text-slate-500">({professor.capacity! - professor.assigned}자리)</em>}</span><button disabled={!enabled} className="btn px-3 py-1.5" onClick={() => state.requestApproval(departmentId, professor.id)}>{enabled ? "승인 요청" : "정원 마감"}</button></div> })}</div></div>; }
