"use client";
import { departments, getDepartment } from "@/data/departments";
import { canApply, deadlineConflicts, nextTask, requiredRoadmaps, progressIndex, missingRequirementMajors, reviewNotice } from "@/lib/rules";
import { useBoardStore } from "@/lib/store";
import type { Application, Department } from "@/lib/types";
import { useState } from "react";

const methodText = {contact_approval:"직접 컨택 후 승인",application:"시스템 신청",course_assigned:"수업에서 배정"};
const colors: Record<string,string> = {violet:"bg-violet-100 text-violet-800",sky:"bg-sky-100 text-sky-800",amber:"bg-amber-100 text-amber-800"};
export function StudentBoard() {
  const state=useBoardStore(), student=state.students.find(s=>s.id===state.activeStudentId) ?? state.students[0];
  const [draft,setDraft]=useState({primary:"",secondary:""}), [tab,setTab]=useState("all");
  const maps=requiredRoadmaps(student,departments), missing=missingRequirementMajors(student,departments);
  const next=nextTask(student,departments,state.applications,state.submissions), conflicts=deadlineConflicts(student,departments);
  const chooser=<label className="block text-sm font-bold">데모 학생<select className="ml-2 rounded-lg border bg-white p-2" value={student.id} onChange={e=>{state.chooseStudent(e.target.value);setTab("all");setDraft({primary:"",secondary:""});}}>{state.students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>;
  if(!student.selectedMajors.length)return <section className="mx-auto max-w-2xl">{chooser}<h1 className="mt-5 text-3xl font-extrabold">전공별 논문 로드맵을 만들어요</h1><p className="mt-3">주전공을 선택하세요. 복수전공은 선택 사항입니다.</p><div className="card mt-6 space-y-5"><MajorSelect label="주전공" value={draft.primary} onChange={v=>setDraft({...draft,primary:v})}/><MajorSelect label="복수전공" value={draft.secondary} onChange={v=>setDraft({...draft,secondary:v})}/><button className="btn" disabled={!draft.primary || draft.primary===draft.secondary} onClick={()=>state.selectMajors([{departmentId:draft.primary,role:"primary"},...(draft.secondary?[{departmentId:draft.secondary,role:"secondary" as const}]:[])])}>전공별 로드맵 생성</button>{draft.primary && draft.primary===draft.secondary && <p role="alert">주전공과 복수전공은 다르게 선택해 주세요.</p>}</div></section>;
  const events=maps.flatMap(({department})=>department.stages.map(stage=>({department,stage}))).sort((a,b)=>a.stage.dueDate.localeCompare(b.stage.dueDate));
  return <div className="space-y-6">
    {chooser}<header><p className="label">학생 · {student.studentNo}</p><h1 className="text-3xl font-extrabold">{student.name}님의 졸업논문 보드</h1><p className="mt-2">{student.graduationSemester} 졸업 예정 · 졸업논문 대상</p></header>
    {missing.map(m=><section role="alert" className="card border-amber-300" key={m.departmentId}><h2 className="font-bold">{getDepartment(m.departmentId)?.name ?? m.departmentId} · {m.role==="primary"?"주전공":"복수전공"}: 정보 확인 필요</h2><p>논문 요건이 누락되어 필수·면제 여부를 판단할 수 없습니다. 학과 행정실에 확인해 주세요.</p></section>)}
    {student.selectedMajors.filter(m=>getDepartment(m.departmentId)?.requirements?.[m.role]==="면제").map(m=><section className="card" key={m.departmentId}>{getDepartment(m.departmentId)?.name} · {m.role==="secondary"?"복수전공":"주전공"} 논문 면제</section>)}
    {next?<section className="rounded-2xl bg-slate-900 p-6 text-white"><p>다음 할 일 · {next.department.name}</p><h2 className="mt-2 text-2xl font-extrabold">{next.stage.name}</h2><p className="mt-2">{next.stage.description}</p><p className="mt-4">마감: {next.stage.dueDate || "정보 확인 필요"} · {next.stage.submissionMethod}</p></section>:maps.length>0 && <p className="card">모든 필수 전공 절차가 완료되었습니다.</p>}
    {conflicts.length>0 && <section role="status" className="rounded-xl bg-amber-50 p-4 text-amber-900"><b>전공별 마감이 같은 주에 겹칩니다.</b>{conflicts.map(c=><p key={c.week}>{c.week} 시작 주 · {c.departmentIds.map(id=>getDepartment(id)?.name).join(" / ")}</p>)}</section>}
    <nav role="tablist" aria-label="전공별 로드맵" className="flex flex-wrap gap-2">{[{id:"all",name:"전체"},...maps.map(m=>m.department)].map(d=><button role="tab" aria-selected={tab===d.id} className={tab===d.id?"btn":"btn-alt"} key={d.id} onClick={()=>setTab(d.id)}>{d.name}</button>)}</nav>
    <section className="grid gap-4 lg:grid-cols-2">{maps.filter(m=>tab==="all" || tab===m.department.id).map(({department,role})=>{
      const app=state.applications.find(a=>a.studentId===student.id && a.departmentId===department.id);
      const index=progressIndex(student.id,department,state.applications,state.submissions), stage=department.stages[index];
      return <article className="card min-w-0" key={department.id}><div className="flex justify-between gap-2"><div><p className="label">{role==="primary"?"주전공":"복수전공"}</p><h2 className="text-xl font-extrabold">{department.name}</h2></div>{department.sourceType!=="실제 공지" && <span className="badge h-fit bg-violet-100 text-violet-700">예시 데이터</span>}</div>
        <div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="지도교수 방식" value={methodText[department.method]}/><Info label="다음 마감" value={stage?stage.dueDate:"완료"}/><Info label="제출 방법" value={stage?stage.submissionMethod:"완료"}/><Info label="공식 링크" value={department.officialLink}/></div>
        <div className="mt-4 space-y-2">{department.stages.map((s,i)=><div key={s.id} className={"rounded-lg p-3 text-sm "+(i<index?"bg-emerald-50 text-emerald-700":i===index?"bg-indigo-50 font-bold text-indigo-800":"bg-slate-50 text-slate-500")}>{i+1}. {s.name}<span className="float-right">{i<index?"완료":i===index?"진행 필요":"예정"}</span></div>)}</div>
        <ApplicationPanel key={student.id+department.id} studentId={student.id} department={department} application={app}/>
        <h3 className="mt-5 font-bold">제출 서류와 문의처</h3><p className="text-xs text-slate-500">제출 여부만 기록합니다. 파일은 업로드되지 않습니다.</p>
        {department.stages.map((s,i)=>{const submitted=state.submissions.find(r=>r.studentId===student.id && r.departmentId===department.id && r.stageId===s.id);return <details className="mt-3 rounded-lg border p-3 text-sm" key={s.id}><summary>{s.name} · {submitted?"제출 완료":i<index?"완료":"미제출"}</summary><div className="mt-3 space-y-2"><p>제출 서류·서식: {s.documents || "정보 확인 필요"}</p><p>제출 방법: {s.submissionMethod} · 증빙: {s.evidence}</p><p>마감: {s.dueDate || "정보 확인 필요"}</p><p>유의사항: {s.notes}</p><p>문의처: {s.contact || "정보 확인 필요"}</p>{submitted && <p>제출 시각: {new Date(submitted.at).toLocaleString("ko-KR")}</p>}{s.id!=="advisor" && <button className="btn" disabled={i!==index || !!submitted} onClick={()=>state.submitStage(department.id,s.id)}>제출 완료 기록</button>}</div></details>;})}
      </article>;
    })}</section>
    <section className="card"><h2 className="text-xl font-extrabold">전공 통합 마감 캘린더</h2><p className="mt-2 text-sm text-slate-500">전체 마감일 · 날짜순 일정 목록</p><div className="mt-4 grid gap-3 md:grid-cols-2">{events.map(({department,stage})=><div className="rounded-xl bg-slate-50 p-4" key={department.id+stage.id}><span data-department={department.id} className={"badge "+(colors[department.color] ?? "bg-slate-200 text-slate-800")}>{department.name}</span><p className="mt-2 font-bold">{stage.dueDate || "정보 확인 필요"} · {stage.name}</p><p className="text-sm">{stage.documents} / {stage.submissionMethod}</p></div>)}</div></section>
  </div>;
}
function MajorSelect({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}) {return <label className="block font-bold">{label}<select aria-label={label} className="mt-2 w-full rounded-xl border bg-white p-3" value={value} onChange={e=>onChange(e.target.value)}><option value="">{label==="복수전공"?"없음":"선택하세요"}</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>;}
function Info({label,value}:{label:string;value:string}) {return <div className="break-words"><p className="label">{label}</p><p className="mt-1 font-bold">{label==="공식 링크" && /^https?:\/\//.test(value)?<a className="underline" href={value} target="_blank" rel="noreferrer">{value}</a>:value || "정보 확인 필요"}</p></div>;}
function ApplicationPanel({studentId,department,application}:{studentId:string;department:Department;application?:Application}) {
  const state=useBoardStore(), [topic,setTopic]=useState("학습 과정에서의 기억 형성"), [plan,setPlan]=useState("가상 연구계획 요약입니다.");
  const professor=state.professors.find(p=>p.id===application?.professorId);
  if(department.method==="course_assigned")return <div className="mt-5 rounded-xl bg-sky-50 p-4 text-sm">{application?<><b>배정 완료 · {professor?.name}</b><p>행정실 배정 결과가 반영되었습니다.</p></>: "행정실이 수업 기반으로 배정합니다. 학생 신청은 필요 없습니다."}</div>;
  return <div className="mt-5 space-y-3">{application && <div className="rounded-xl bg-slate-100 p-4 text-sm"><b>신청 상태: {application.status}</b><p>신청 교수: {professor?.name}</p><p>신청일: {application.requestedAt.slice(0,10)}</p><p>행정실 검토: {application.adminReview}</p>{reviewNotice(application) && <p className="mt-2 font-bold text-indigo-700">{reviewNotice(application)}</p>}{application.feedback && <p className="mt-2 text-rose-700">피드백: {application.feedback}</p>}</div>}
    {(!application || ["수정 요청","면담 요청","반려"].includes(application.status)) && <><label className="block text-sm">연구 주제<input className="mt-1 w-full rounded border p-2" value={topic} onChange={e=>setTopic(e.target.value)}/></label><label className="block text-sm">연구계획<textarea className="mt-1 w-full rounded border p-2" value={plan} onChange={e=>setPlan(e.target.value)}/></label>{state.professors.filter(p=>p.departmentId===department.id).map(p=>{
      const contacted=state.contacts.some(c=>c.studentId===studentId && c.professorId===p.id), capacity=canApply(department,p), enabled=capacity && (department.method!=="contact_approval" || contacted) && !!topic.trim() && !!plan.trim();
      return <div className="rounded-xl border p-3 text-sm" key={p.id}><b>{p.name}</b><p>{p.keywords.join(" · ")} · {p.topics}</p>{department.usesCapacity && <p>남은 자리: {(p.capacity ?? 0)-p.assigned}</p>}<div className="mt-2 flex flex-wrap gap-2">{department.method==="contact_approval" && <button className="btn-alt" disabled={contacted} onClick={()=>state.recordContact(department.id,p.id)}>{contacted?"컨택 완료 기록됨":"교수 컨택 완료"}</button>}<button className="btn" disabled={!enabled} onClick={()=>state.requestApproval(department.id,p.id,topic,plan)}>{!capacity?"정원 마감":"승인 요청"}</button></div></div>;
    })}</>}
  </div>;
}
